### ISSUE TITLE
Amazing project!

### ISSUE THREAD

**Issue by hermanzdosilovic** [wujr5/docker-simple-ucp#1]
@wujr5 thanks for starting this project! How long will it take for first release? I would like to try it out for my team.

**Comment by wujr5** [comment]
@hermanzdosilovic  Sorry for being late to see this issue. This project is a toy project, it is some kind of imitation of the official UCP of docker. You may like to see this: https://docs.docker.com/datacenter/ucp/1.1/. Thanks.
